// What the setup steps tell each other, and why it is not stdout.
//
// `demo-setup.mjs` runs the three setup scripts in order and has to know what each one decided:
// did readiness say GO, which version did it pick, how many items did prep leave, did the
// injection check hold. All of that is already printed — and a summary scraped out of printed
// text is a contract nobody declared. It breaks when a sentence is reworded, and it breaks
// silently, which is the only kind of breakage that reaches a recording.
//
// So each script writes the few values it decided into one small JSON file, and the orchestrator
// reads that. The console output is unchanged and stays the thing a person reads; this is the
// thing a program reads. Two audiences, two channels, neither pretending to be the other.
//
// MERGED, NEVER OVERWRITTEN. Each script owns its own key and leaves the rest alone, so running
// one of them by hand does not erase what the others found.
//
// Gitignored: it describes one machine at one moment and is regenerated by every setup run.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Absolute, from this file rather than from the working directory — these scripts are launched
// by a double-clicked .cmd as well as from a prompt, and cwd is not the same in both.
export const STATE_PATH = join(dirname(fileURLToPath(import.meta.url)), '.demo-state.json');

export function readState() {
  try { return JSON.parse(readFileSync(STATE_PATH, 'utf8')); } catch { return {}; }
}

/** Merge one step's findings in. Never throws: telemetry may fail, the product may not. */
export function writeState(key, value) {
  try {
    const state = readState();
    state[key] = { ...value, at: new Date().toISOString() };
    writeFileSync(STATE_PATH, JSON.stringify(state, null, 2), 'utf8');
  } catch (e) {
    console.log(`  (could not record state for the setup launcher: ${e.message})`);
  }
}
